# stocks_list.py
# This file contains a pre-loaded list of Nifty 50, Nifty Next 50, and top Midcap stocks.
# We use ~150 highly liquid stocks so the screener can run within a minute or two.
# To scan the entire Nifty 500, you can add more symbols to this list, 
# but be aware that it might take several minutes to download data for all 500.

NIFTY_STOCKS = [
    # Nifty 50
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'BHARTIARTL.NS',
    'SBIN.NS', 'INFY.NS', 'LT.NS', 'ITC.NS', 'HINDUNILVR.NS', 'AXISBANK.NS',
    'BAJFINANCE.NS', 'MARUTI.NS', 'KOTAKBANK.NS', 'HCLTECH.NS', 'ASIANPAINT.NS',
    'TATAMOTORS.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'NTPC.NS', 'BAJAJFINSV.NS',
    'POWERGRID.NS', 'ULTRACEMCO.NS', 'TITAN.NS', 'M&M.NS', 'WIPRO.NS', 'JSWSTEEL.NS',
    'ADANIENT.NS', 'ADANIPORTS.NS', 'COALINDIA.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 
    'BAJAJ-AUTO.NS', 'GRASIM.NS', 'TECHM.NS', 'HINDALCO.NS', 'CIPLA.NS',
    'EICHERMOT.NS', 'TATACONSUM.NS', 'BRITANNIA.NS', 'APOLLOHOSP.NS', 'DRREDDY.NS', 
    'DIVISLAB.NS', 'INDUSINDBK.NS', 'HEROMOTOCO.NS', 'BPCL.NS', 'UPL.NS', 'ONGC.NS',
    
    # Nifty Next 50 (Subset)
    'HAL.NS', 'BEL.NS', 'BHEL.NS', 'IRFC.NS', 'JINDALSTEL.NS', 'TRENT.NS',
    'TVSMOTOR.NS', 'CHOLAFIN.NS', 'PNB.NS', 'BANKBARODA.NS', 'DLF.NS',
    'ZOMATO.NS', 'JIOFIN.NS', 'VBL.NS', 'PIDILITIND.NS', 'GODREJCP.NS',
    'SIEMENS.NS', 'SHREECEM.NS', 'HAVELLS.NS', 'GAIL.NS', 'SRF.NS',
    'BOSCHLTD.NS', 'CUMMINSIND.NS', 'AUBANK.NS', 'CANBK.NS', 'ICICIGI.NS',
    'ICICIPRULI.NS', 'COLPAL.NS', 'MARICO.NS', 'DABUR.NS', 'MCDOWELL-N.NS',
    'TORNTPHARM.NS', 'LUPIN.NS', 'AUROPHARMA.NS', 'PIIND.NS', 'ZYDUSLIFE.NS', 
    'ALKEM.NS', 'PETRONET.NS', 'MUTHOOTFIN.NS', 'RECLTD.NS', 'PFC.NS', 
    'HDFCAMC.NS', 'INDIGO.NS', 'NAUKRI.NS', 'MCX.NS', 'PAYTM.NS', 'NYKAA.NS', 
    'POLICYBZR.NS', 'DELHIVERY.NS', 'LICHSGFIN.NS', 'TATACHEM.NS',
    
    # Midcap / Others
    'SAIL.NS', 'NMDC.NS', 'NATIONALUM.NS', 'AMBUJACEM.NS', 'ACC.NS',
    'BANDHANBNK.NS', 'IDFCFIRSTB.NS', 'FEDERALBNK.NS', 'YESBANK.NS', 'ZEEL.NS',
    'SUNTV.NS', 'IGL.NS', 'MGL.NS', 'GUJGASLTD.NS', 'MRF.NS', 'APOLLOTYRE.NS',
    'BATAINDIA.NS', 'VOLTAS.NS', 'CROMPTON.NS', 'DIXON.NS', 'POLYCAB.NS',
    'KEI.NS', 'HINDCOPPER.NS', 'ASTRAL.NS', 'SUPREMEIND.NS', 'IRCTC.NS',
    'CONCOR.NS', 'RVNL.NS', 'IRCON.NS', 'MAZDOCK.NS', 'COCHINSHIP.NS',
    'GRSE.NS', 'BSE.NS', 'CDSL.NS', 'CAMS.NS', 'KFINTECH.NS', 'ANGELONE.NS',
    'UTIAMC.NS', 'RADICO.NS', 'UBL.NS', 'BALRAMCHIN.NS', 'TRIDENT.NS',
    'WELSPUNLIV.NS', 'RAYMOND.NS', 'PAGEIND.NS', 'JUBLFOOD.NS', 'DEEPAKNTR.NS',
    'TATACOMM.NS', 'ABCAPITAL.NS', 'ABFRL.NS', 'IDEA.NS'
]
